"""watchLater table

Revision ID: 594ae58633bf
Revises: cb6361324471
Create Date: 2021-01-13 13:27:38.570286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594ae58633bf'
down_revision = 'cb6361324471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchLists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stock', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchLists')
    # ### end Alembic commands ###
