"""plan table

Revision ID: cb6361324471
Revises: 41be2ab01b40
Create Date: 2021-01-13 13:07:40.051322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6361324471'
down_revision = '41be2ab01b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('job', sa.String(length=100), nullable=False),
    sa.Column('monthlyIncome', sa.Integer(), nullable=False),
    sa.Column('stock', sa.String(length=100), nullable=False),
    sa.Column('amountToSave', sa.Integer(), nullable=False),
    sa.Column('targetAmountToInvest', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plans')
    # ### end Alembic commands ###
