"""stock table

Revision ID: 41be2ab01b40
Revises: b0789838126e
Create Date: 2021-01-11 10:40:50.184399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41be2ab01b40'
down_revision = 'b0789838126e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockInfos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stock', sa.String(length=100), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('pps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stockInfos')
    # ### end Alembic commands ###
